# Generated by Django 3.0.5 on 2020-04-10 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale_name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=8)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('region', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('timezone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=200)),
                ('page_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sublocale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sublocale_name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=8)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('region', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('timezone', models.CharField(max_length=200)),
                ('parent_locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifieds.Locale')),
            ],
        ),
        migrations.CreateModel(
            name='Classified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classified_title', models.CharField(max_length=200)),
                ('classified_text', models.TextField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifieds.Locale')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifieds.Section')),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifieds.Subsection')),
            ],
        ),
    ]
