# Generated by Django 3.0.5 on 2020-04-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locale',
            old_name='country',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='sublocale',
            old_name='country',
            new_name='area',
        ),
    ]
