# Generated by Django 3.0.5 on 2020-04-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0002_auto_20200411_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locale',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='locale',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='locale',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='sublocale',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sublocale',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='sublocale',
            name='timezone',
        ),
    ]
