# Generated by Django 3.0.5 on 2020-04-11 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0003_auto_20200411_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='locale',
            name='area',
        ),
        migrations.RemoveField(
            model_name='sublocale',
            name='area',
        ),
        migrations.AddField(
            model_name='locale',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classifieds.Province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sublocale',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classifieds.Province'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locale',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifieds.Region'),
        ),
        migrations.AlterField(
            model_name='sublocale',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifieds.Region'),
        ),
    ]
