# Generated by Django 3.0.5 on 2020-04-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0004_auto_20200411_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classifieds.Region'),
            preserve_default=False,
        ),
    ]
